import logo from './logo.svg';
import arrowDown from './arrow-down.svg';
import home from './Home.svg';
import cart from './Cart.svg';
import like from './Like.svg';
import menu from './Menu.svg';
import search from './Search.svg';
import close from './Close.svg';
import likeFilled from './like-filled.svg';